//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.27 at 10:47:33 AM ICT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://service.payment.com/mps", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.payment.service.mps;
